### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by snhirsch** [joshbuhler/SpeedShop#26]
Would be helpful.  I'm comfortable with software development concepts, but not under X-Code.  Even a little handwaving is better than nothing.

**Comment by joshbuhler** [comment]
I guess I should check the issues more often. A late response is better than none though.

The instructions for building the app at the time was to use Xcode. Open the `.xcodeproj` file in Xcode, use the Product > Build menu option, and it would build. I don't have instructions for a different workflow.
