### ISSUE TITLE
How do I get SpeedShop?

### ISSUE THREAD

**Issue by rob-va** [joshbuhler/SpeedShop#27]
Hi Josh,

The OneDrive link isn't working, and I'm not a coder. (yet...)

Thanks,

Rob

**Comment by joshbuhler** [comment]
I'm no longer supporting this app, but I've moved the most recent build into the source code folder. Downloading the source from either the project page or the info page will also include that built version of the app.

As for whether it works or not on the latest versions of macOS, I don't really know. I launched it in macOS 10.12.6, and it ran, but I don't have a way of actually using it anymore. Good luck!
